const promptList = [
    "Shibou's metal music",
    "Lurker appears",
    "TastyPi maths",
    "Edgy Jocose",
    "Meowz friend gc",
    "Cute Usaken",
    "Cannibalism mention",
    "Jerry with DnD",
    "Phobi appears & leaves",
    "Vovgus & Phobi flirting",
    "\"I miss my wife\"",
    "Shrimp insults Cris",
    "Actually serious",
    "Narwhal karaoke",
    "Shad dropping wisdom",
    "Jocose being a cute bf",
    "Random Terra gif",
    "Move to #silliness",
    "Ddouble being old",
    "Actually wholesome",
    "Multi convo chat",
    "No romance Meowz",
    "Flustered Cris",
    "Bullied Cris",
    "Mage boy coding/game dev progress",
    "Anonum mentions Project Moon",
    "\"Grumble\"",
    "\"I love my wife\"",
    "Anonum with science/math",
    "Jerry Six Simp",
    "Jerry xkcd comic",
];
const freeList = [
    "Therapy",
    "Jocussy"
];
